server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    min-spare-threads: 30
spring:
  profiles:
    active: dev
  devtools:
    restart:
      enabled: false
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    mode: HTML5
    prefix: classpath:/templates/ares/
    suffix: .html
    #指定编码
    encoding: utf-8
    #禁用缓存 默认false
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: AresScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    job-store-type: jdbc
#消息配置
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#    listener:
#      simple:
#        concurrency: 10
#        max-concurrency: 20
#        prefetch: 5
#  kafka:
#    bootstrap-servers: 127.0.0.1:9092
#    producer:
#      retries: 0
#      batch-size: 16384
#      buffer-memory: 33554432
#      acks: 1
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    consumer:
#      group-id: testGroup
#      auto-offset-reset: earliest
#      enable-auto-commit: true
#      auto-commit-interval: 100
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

mybatis:
  mapper-locations: classpath:mapping/**/*.xml
  type-aliases-package: com.system.springbootV1.**.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#分页配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#日志配置
logging:
  config: classpath:logback-spring.xml
path:
  log: logs

# Spring Boot Actuator:健康检查、审计、统计和监控 配置
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  # Use "*" to expose all endpoints, or a comma-separated [health,info] list to expose selected ones
  endpoints:
    web:
      exposure:
        include: ["*"]
        exclude:
#info:
#  app:
#    name: @project.name@
#    description: @project.description@
#    version: @project.version@
#    encoding: @project.build.sourceEncoding@
#    java:
#      version: @java.version@

#基本配置信息
ares:
  base:
    name: ARES
    version: 1.0.0
    copyright: 2020-2020@${ares.base.name}-${ares.base.version}
    #全局session时间
    timeout: 3600
    #前后端分离配置
    separate: true
  #代码生成配置
  codegenerator:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbootv1?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: root
    databaseName: springbootv1
    tableName: test_v
    tablePrefix:
    genenaterLevel: 1
    basePackage: com.system.springbootv1.project.model
    daoPackage: com.system.springbootv1.project.dao
    xmlDir: .src.main.resources.mapping.project
    servicePackage: com.system.springbootv1.project.service
    controllerPackage: com.system.springbootv1.project.controller

