server:
  port: 8080
spring:
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    #指定编码
    encoding: utf-8
    #禁用缓存 默认false
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#    listener:
#      simple:
#        concurrency: 10
#        max-concurrency: 20
#        prefetch: 5
#  kafka:
#    bootstrap-servers: 127.0.0.1:9092
#    producer:
#      retries: 0
#      batch-size: 16384
#      buffer-memory: 33554432
#      acks: 1
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    consumer:
#      group-id: testGroup
#      auto-offset-reset: earliest
#      enable-auto-commit: true
#      auto-commit-interval: 100
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.system.springbootV1.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  config: classpath:logback-spring.xml
path:
  log: logs

ares:
  base:
    name: ares
    version: 1.0.0
    copyright: 2020-${ares.base.name}-${ares.base.version}
  codegenerator:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbootv1?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: root
    databaseName: springbootv1
    tableName: test_v
    tablePrefix:
    genenaterLevel: 1
    basePackage: com.system.springbootv1.model
    daoPackage: com.system.springbootv1.dao
    xmlDir: .src.main.resources.mapping
    servicePackage: com.system.springbootv1.service
    controllerPackage: com.system.springbootv1.controller



